# Generated by Django 4.2.3 on 2023-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=700)),
                ('nomer', models.CharField(max_length=300)),
                ('yoqish', models.CharField(max_length=100)),
            ],
        ),
    ]
